#!/bin/bash

set -e
if [[ "$#" -lt 1 ]]; then
    echo "PCI Addresses not provided, nothing to do"
    exit
fi

# shellcheck disable=SC1091
source /etc/vhostuser-bind.conf

function bindDriver() {
    local dev=$1

    devlink="/sys/bus/pci/devices/$dev"

    if [[ -f "$devlink" ]]; then
        syspath=$(realpath "$devlink")
        if [ ! -f "$syspath/driver/unbind" ]; then
            echo "File $syspath/driver/unbind not found"
            return 1
        fi
        if ! echo "$dev" >"$syspath/driver/unbind"; then
            return 1
        fi

        if [ ! -f "$syspath/driver_override" ]; then
            echo "File $syspath/driver_override not found"
            return 1
        fi
        if ! echo "vfio-pci" >"$syspath/driver_override"; then
            return 1
        fi

        if [ ! -f "/sys/bus/pci/drivers/vfio-pci/bind" ]; then
            echo "File /sys/bus/pci/drivers/vfio-pci/bind not found"
            return 1
        fi
        if ! echo "$dev" >"/sys/bus/pci/drivers/vfio-pci/bind"; then
            return 1
        fi
        return 0
    else
        echo "PCI device $devlink does not exist, skipping..."
    fi

    return 1
}

# The pci addresses for each network to be bound to the vfio driver
# has been set in the /etc/vhostuser-bind.conf as a space-seperated
# string. Loop through the pci addresses and bind to the vfio-pci
# driver.
for pci_address in "$@"; do
    bindDriver "$pci_address"
done
