apiVersion: v1
kind: Pod
metadata:
 name: testpmd
 namespace: default
 annotations:
   k8s.v1.cni.cncf.io/networks: "uplink1,uplink2"
spec:
 containers:
 - name: testpmd
   command: ["/bin/sh"]
   args: ["-c", "testpmd -l $(taskset -pc 1 | cut -d: -f2) --in-memory -w 00:04.0 -w 00:05.0 --socket-mem 1024 -n 4 -- --nb-cores=1 --auto-start --forward-mode=mac --stats-period 10"]
   image: registry.redhat.io/openshift4/dpdk-base-rhel8:v4.6
   securityContext:
     privileged: true
     runAsUser: 0
   resources:
     requests:
       memory: 1000Mi
       hugepages-1Gi: 3Gi
       cpu: '3'
     limits:
       hugepages-1Gi: 3Gi
       cpu: '3'
       memory: 1000Mi
   volumeMounts:
     - mountPath: /dev/hugepages
       name: hugepage
       readOnly: False
 volumes:
 - name: hugepage
   emptyDir:
     medium: HugePages

