spec:
  additionalNetworks: 
  - name: vhostuser1
    namespace: example-cnf
    type: Raw
    rawCNIConfig: '{
      "cniVersion": "0.3.1",
      "name": "hostonly",
      "type": "host-device",
      "pciBusId": "0000:00:04.0",
      "ipam": { }
    }'
  - name: vhostuser2
    namespace: example-cnf
    type: Raw
    rawCNIConfig: '{
      "cniVersion": "0.3.1",
      "name": "hostonly",
      "type": "host-device",
      "pciBusId": "0000:00:05.0",
      "ipam": { }
    }'
